# Heart Disease Analysis

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.ensemble import RandomForestRegressor

## Load Dataset

In [90]:
df = pd.read_csv("heart_disease.csv")
df.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

## Basic Info

In [91]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HeartDiseaseorAttack  253476 non-null  float64
 1   HighBP                253452 non-null  float64
 2   HighChol              253467 non-null  float64
 3   CholCheck             253467 non-null  float64
 4   BMI                   253470 non-null  float64
 5   Smoker                253445 non-null  float64
 6   Stroke                253482 non-null  float64
 7   Diabetes              253457 non-null  float64
 8   PhysActivity          253464 non-null  float64
 9   Fruits                253466 non-null  float64
 10  Veggies               253460 non-null  float64
 11  HvyAlcoholConsump     253460 non-null  float64
 12  AnyHealthcare         253455 non-null  float64
 13  NoDocbcCost           253451 non-null  float64
 14  GenHlth               253467 non-null  float64
 15  MentHlth              253464 non-null  float64
 16  PhysHlth              253477 non-null  float64
 17  DiffWalk              253449 non-null  float64
 18  Sex                   253450 non-null  float64
 19  Age                   253468 non-null  float64
 20  Education             253469 non-null  float64
 21  Income                253452 non-null  float64
dtypes: float64(22)
memory usage: 42.6 MB

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253476.000000,253452.000000,253467.000000,253467.000000,253470.000000,253445.000000,253482.000000,253457.000000,253464.000000,253466.000000,...,253455.000000,253451.000000,253467.000000,253464.000000,253477.000000,253449.000000,253450.000000,253468.000000,253469.000000,253452.000000
mean,0.094186,0.429008,0.424114,0.962666,28.382467,0.443134,0.040571,0.296914,0.756518,0.634255,...,0.951072,0.084190,2.511376,3.185506,4.242156,0.168227,0.440383,8.032126,5.050515,6.053852
std,0.292088,0.494935,0.494209,0.189580,6.609107,0.496757,0.197294,0.698147,0.429185,0.481639,...,0.215718,0.277673,1.068481,7.413680,8.718150,0.374069,0.496434,3.054265,0.985725,2.071116
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [92]:
df.shape

(253680, 22)

## Check Missing Values & Duplicates

In [93]:
df.isna().sum()

HeartDiseaseorAttack    204
HighBP                  228
HighChol                213
CholCheck               213
BMI                     210
Smoker                  235
Stroke                  198
Diabetes                223
PhysActivity            216
Fruits                  214
Veggies                 220
HvyAlcoholConsump       220
AnyHealthcare           225
NoDocbcCost             229
GenHlth                 213
MentHlth                216
PhysHlth                203
DiffWalk                231
Sex                     230
Age                     212
Education               211
Income                  228
dtype: int64

In [94]:
# Count rows that contain at least one missing value
df.isna().any(axis=1).sum()

np.int64(1358)

In [95]:
# Count duplicate rows
df.duplicated().sum()

np.int64(23697)

## Drop Missing & Duplicates

In [96]:
df_clean = df.dropna()

In [97]:
print("Total rows after dropping missing values:", df_clean.shape[0], "\n")

Total rows after dropping missing values: 252322

In [98]:
df_clean = df_clean.drop_duplicates()

In [99]:
print("Total rows after dropping missing values & duplicates:", df_clean.shape[0], "\n")

Total rows after dropping missing values & duplicates: 228625

In [100]:
df_clean.shape

(228625, 22)

## Feature Engineering

### 1. BMI Winsorization

In [101]:
bmi_low, bmi_high = df_clean["BMI"].quantile([0.01, 0.99])
df_clean["BMI_capped"] = df_clean["BMI"].clip(bmi_low, bmi_high)

### 2. General Health Mapping

In [102]:
genhlth_map = {1: "Excellent", 2: "Very Good", 3: "Good", 4: "Fair", 5: "Poor"}
df_clean["GenHlth_Factor"] = df_clean["GenHlth"].map(genhlth_map)

### 3. Filter Invalid Health Values

In [103]:
df_clean = df_clean[(df_clean["MentHlth"] <= 30) & (df_clean["PhysHlth"] <= 30)]

### 4. BMI Categories

In [104]:
df_clean["BMI_Category"] = pd.cut(
    df_clean["BMI"],
    bins=[0, 18.5, 25, 30, float("inf")],
    labels=["Underweight", "Normal", "Overweight", "Obese"]
)

### 5. Age Group Mapping

In [105]:
age_labels = [
    "18-24","25-29","30-34","35-39","40-44","45-49",
    "50-54","55-59","60-64","65-69","70-74","75-79","80+"
]
df_clean["AgeGroup"] = df_clean["Age"].astype(int).apply(lambda x: age_labels[x-1])

### 6. Age Bands

In [106]:
df_clean["AgeBand"] = pd.cut(
    df_clean["Age"],
    bins=[0,3,6,9,11,14],
    labels=["18-34","35-49","50-64","65-74","75+"]
)

### 7. Risk Score

In [107]:
df_clean["RiskScore"] = (
    df_clean["Smoker"] +
    df_clean["HvyAlcoholConsump"] +
    (1 - df_clean["PhysActivity"]) +
    (1 - df_clean["Fruits"]) +
    (1 - df_clean["Veggies"])
)

### 8. Disease Count

In [108]:
df_clean["DiseaseCount"] = (
    df_clean["HighBP"] + df_clean["HighChol"] +
    df_clean["Diabetes"] + df_clean["Stroke"]
)

### 9. Health Stress Index

In [109]:
df_clean["HealthStressIndex"] = df_clean["MentHlth"] + df_clean["PhysHlth"]

### 10. Healthcare Access Score

In [110]:
df_clean["HealthcareScore"] = df_clean["AnyHealthcare"] + (1 - df_clean["NoDocbcCost"])

### 11. Obesity Flag

In [111]:
df_clean["ObeseFlag"] = (df_clean["BMI"] >= 30).astype(int)

### 12. Lifestyle Profile

In [112]:
df_clean["LifestyleProfile"] = pd.cut(
    df_clean["RiskScore"],
    bins=[-1,1,3,10],
    labels=["Healthy","ModerateRisk","HighRisk"]
)

In [113]:
df_clean.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,GenHlth_Factor,BMI_Category,AgeGroup,AgeBand,RiskScore,DiseaseCount,HealthStressIndex,HealthcareScore,ObeseFlag,LifestyleProfile
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,Poor,Obese,60-64,50-64,3.0,2.0,33.0,2.0,1,ModerateRisk
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,Good,Normal,50-54,50-64,3.0,0.0,0.0,0.0,0,ModerateRisk
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,Poor,Overweight,60-64,50-64,2.0,2.0,60.0,1.0,0,ModerateRisk
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,Very Good,Overweight,70-74,65-74,0.0,1.0,0.0,2.0,0,Healthy
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,Very Good,Normal,70-74,65-74,0.0,2.0,3.0,2.0,0,Healthy

## Train / Validation / Test Split

In [115]:
target_col = "HeartDiseaseorAttack"

numeric_features = [
    "Age","PhysHlth","MentHlth","HealthStressIndex",
    "DiseaseCount","ObeseFlag","RiskScore","BMI",
    "Sex","HighBP","HighChol","Diabetes","Stroke",
    "Smoker","PhysActivity"
]

categorical_features = ["AgeGroup","AgeBand","LifestyleProfile"]

X = df_clean[numeric_features + categorical_features]
y = df_clean[target_col]

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=123
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=123
)